# Generated by Django 2.1.5 on 2019-03-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='browse',
            field=models.IntegerField(default=0, help_text='记录活动浏览量', verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='article',
            name='browse',
            field=models.IntegerField(default=0, help_text='记录文章浏览量', verbose_name='浏览量'),
        ),
    ]
