# Generated by Django 2.1.9 on 2019-08-18 16:26

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(help_text='记录文章图', upload_to=app.models.ArticleImage.get_upload_to)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(help_text='记录文章封面图 DELETE', null=True, upload_to=app.models.Article.get_upload_to, verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
    ]
