# Generated by Django 2.1.9 on 2019-08-18 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190819_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Update 时间', verbose_name='Update 时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Article'),
        ),
    ]
