# Generated by Django 2.1.5 on 2019-03-20 10:24

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190320_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ImageField(default=1, help_text='记录文章封面图', upload_to=app.models.Article.get_upload_to, verbose_name='封面图'),
            preserve_default=False,
        ),
    ]
