# Generated by Django 2.1.5 on 2019-08-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190819_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(0, '未完善'), (0, '完善')], default=1, help_text='未完善文章，未完善文章不展示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(default='C', help_text='记录论坛文章的标题', max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(default='C', help_text='记录论坛文章内容', null=True, verbose_name='内容'),
        ),
    ]
