# Generated by Django 2.1.5 on 2019-08-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190825_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.IntegerField(choices=[(1, '未完善'), (0, '完善')], default=1, help_text='未完善文章，未完善文章不展示'),
        ),
    ]
