# Generated by Django 2.1.5 on 2019-03-21 13:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190321_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images',
            field=models.ImageField(help_text='记录文章封面图', null=True, upload_to=app.models.Article.get_upload_to, verbose_name='封面图'),
        ),
    ]
