# Generated by Django 2.1.5 on 2019-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190321_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='verify',
            field=models.BooleanField(default=False, help_text='记录活动发布后[是否需要|是否完成]审核', verbose_name='审核'),
        ),
        migrations.AddField(
            model_name='article',
            name='verify',
            field=models.BooleanField(default=False, help_text='记录文章发布后[是否需要|是否完成]审核', verbose_name='审核'),
        ),
    ]
