# Generated by Django 2.1.9 on 2019-09-07 17:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190908_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classactivity',
            name='image',
            field=models.ImageField(help_text='记录标签图', null=True, upload_to=app.models.ClassActivity.get_upload_to),
        ),
    ]
