# Generated by Django 2.1.9 on 2019-09-07 17:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190908_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='name',
            field=models.CharField(default=1, help_text='标签', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='file',
            field=models.ImageField(help_text='记录文章图', null=True, upload_to=app.models.ArticleImage.get_upload_to),
        ),
    ]
