# Generated by Django 2.1.9 on 2019-09-08 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190908_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='class_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ClassActivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_image', to='app.Article'),
        ),
    ]
