# Generated by Django 2.1.5 on 2019-10-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(blank=True, max_length=50, null=True)),
                ('expires_in', models.IntegerField(blank=True, help_text='access_token有效的时间，单位是秒', null=True)),
                ('code', models.IntegerField(default=0, help_text='为一个非0的整数值，表示发生了错误，具体值的含义没有约定。')),
                ('msg', models.CharField(blank=True, help_text='用来说明错误原因，可能在页面上显示给用户', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(help_text='正整数，小于2的32次方。用户在合作方应用的唯一标识。 由合作方应用提供，秀米将使用其作为用户在秀米的身份标识。')),
                ('route_type', models.CharField(default='article', help_text='登录后使用的功能，当前固定为article，表示“图文编辑器”', max_length=10)),
                ('timestamp', models.IntegerField(help_text='当前UNIX时间戳，单位：秒。')),
                ('appid', models.CharField(help_text='合作方应用在秀米平台的唯一标识，由秀米提前颁发，形式为一个32个字符的字符串。', max_length=50)),
                ('nonce', models.CharField(help_text='随机字符串，由合作方应用在每一次签名时生成，使用于签名算法内。', max_length=10)),
                ('signature', models.CharField(help_text='每次登录时根据各项参数计算得出的签名字符串。算法见下面的说明.', max_length=50)),
            ],
        ),
    ]
