# Generated by Django 2.1.5 on 2019-11-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xiumi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(blank=True, help_text='是该图文在秀米的唯一编号', null=True)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='是一个HTML格式的字符串，包含图文内容。', null=True)),
                ('picurl', models.ImageField(blank=True, null=True, upload_to='')),
                ('showCover', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('articles_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='xiumi.SomePathForArticles')),
            ],
        ),
    ]
