# Generated by Django 2.1.5 on 2019-11-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xiumi', '0002_somearticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='somearticles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='somearticles',
            name='picurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
