# Generated by Django 2.1.9 on 2019-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(blank=True, help_text='获取到的凭证', null=True)),
                ('expires_in', models.IntegerField(blank=True, help_text='凭证有效时间，单位：秒', null=True)),
                ('errcode', models.IntegerField(choices=[(-1, '系统繁忙，此时请开发者稍候再试'), (0, '请求成功'), (40001, 'AppSecret错误或者AppSecret不属于这个公众号，请开发者确认AppSecret的正确性'), (40002, '请确保grant_type字段值为client_credential'), (40164, '调用接口的IP地址不在白名单中，请在接口IP白名单中进行设置。（小程序及小游戏调用不要求IP地址在白名单内。）')], help_text='返回错误码')),
                ('errmsg', models.TextField(blank=True, help_text='返回错误信息', null=True)),
            ],
        ),
    ]
