# Generated by Django 2.1.9 on 2019-11-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20191101_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinaccesstoken',
            name='errcode',
            field=models.IntegerField(choices=[(-1, '系统繁忙，此时请开发者稍候再试'), (0, '请求成功'), (40001, 'AppSecret错误或者AppSecret不属于这个公众号，请开发者确认AppSecret的正确性'), (40002, '请确保grant_type字段值为client_credential'), (40164, '调用接口的IP地址不在白名单中，请在接口IP白名单中进行设置。（小程序及小游戏调用不要求IP地址在白名单内。）')], default=0, help_text='返回错误码'),
        ),
    ]
