# Generated by Django 2.1.9 on 2019-11-04 07:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20191101_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weixinaccesstoken',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='weixinaccesstoken',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='添加时间'),
            preserve_default=False,
        ),
    ]
